import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";
import MapboxMap from "~/components/MapboxMap";
import SearchBox from "~/components/SearchBox";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>StreetSweeper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div> */}

        <SearchBox />
        {/* <MapboxMap /> */}
      </main>
    </>
  );
}
